# Generated by Django 5.2.6 on 2025-09-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correntista',
            fields=[
                ('CorrentistaID', models.IntegerField(primary_key=True, serialize=False)),
                ('NomeCorrentista', models.CharField(max_length=50)),
                ('Saldo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'Correntistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('MovimentacaoID', models.IntegerField(primary_key=True, serialize=False)),
                ('TipoOperacao', models.CharField(max_length=1)),
                ('ValorOperacao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DataOperacao', models.DateTimeField()),
                ('Descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Movimentacoes',
                'managed': False,
            },
        ),
    ]
