# Generated by Django 5.2.6 on 2025-09-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcelao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwExtrato',
            fields=[
                ('MovimentacaoID', models.IntegerField(primary_key=True, serialize=False)),
                ('CorrentistaID', models.IntegerField()),
                ('NomeCorrentista', models.CharField(max_length=50)),
                ('TipoOperacao', models.CharField(max_length=7)),
                ('Descricao', models.CharField(max_length=50)),
                ('DataOperacao', models.DateTimeField()),
                ('ValorOperacao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BeneficiarioID', models.IntegerField(null=True)),
                ('NomeBeneficiario', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'vwExtrato',
                'managed': False,
            },
        ),
    ]
